services:
  - type: web
    name: our-area-backend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: TURSO_DB_URL
        sync: false
      - key: TURSO_DB_TOKEN
        sync: false
      - key: SECRET_KEY
        sync: false