services:
  - type: web
    name: our-area-backend
    runtime: python3
    region: singapore
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    healthCheckPath: /docs
    autoDeploy: true
    envVars:
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
    buildFilter:
      paths:
        - main.py
        - requirements.txt
        - render.yaml
        - schema.sql
        - turso_queries.sql
        - api/**
      ignoredPaths:
        - "*.md"
        - ".git/**"
        - "__pycache__/**"
        - "*.pyc"